### PR TITLE
Use new base 32 encode and decode

### PR DESCRIPTION
**Pull request by kldeb**
Fix for issue https://github.com/epicweb-dev/totp/issues/8 

This package is used by remix-auth-totp package which is breaking when deployed to aws lambda using sst. 

The proposed fix in this PR was tested inside the project where I was experiencing the issue. I had to alter the tests slightly to make them work. Not sure if these changes imply any breaking changes. 

Related issue in remix-auth-totp: https://github.com/dev-xo/remix-auth-totp/issues/69

Related PR in remix-auth-totp: https://github.com/dev-xo/remix-auth-totp/pull/70

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
This is fine and should not require a major version bump since thirty-two is not part of the public API. Thanks!

**Comment by kentcdodds** [comment]
Whoops, looks like this broke TypeScript. Could you look into that please? The automated release can't go out until that's fixed.

**Comment by kldeb** [comment]
@kentcdodds can you point me to the issue? I don't see any support for type checking in the scripts...

**Comment by kentcdodds** [comment]
Here it is: https://github.com/epicweb-dev/totp/actions/runs/10605715942/job/29395070639#step:5:1

**Pull request merged**
